sudo: required

services:
  - docker

before_install:
  - docker build -t kukoldnetes/09prod_front -f ./client/Dockerfile.dev ./client

# anything exists here with non-zero status, the build will be failed
# so, basically it's tests place
script:
  - docker run kukoldnetes/09prod_front yarn test

# deployment step
after_success:
  - docker build -t kukoldnetes/09prod_front ./client
  - docker build -t kukoldnetes/09prod_nginx ./nginx
  - docker build -t kukoldnetes/09prod_worker ./worker
  - docker build -t kukoldnetes/09prod_server ./server

  # Log in to the docker cli
  - echo "$DOCKER_SECRET" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # push images to the docker hub
  - docker push kukoldnetes/09prod_front
  - docker push kukoldnetes/09prod_nginx
  - docker push kukoldnetes/09prod_worker
  - docker push kukoldnetes/09prod_server

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-771818164609"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  skip_cleanup: true